# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, scratchllnl ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile_systemc_clang:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: "rseac/systemc-clang:clang-11.0.0"
      options: -v ${{github.workspace}}:/systemc-clang
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build systemc-clang and run tests
        run: |
          cd /systemc-clang-build 
          cmake /systemc-clang -DHDL=ON -DENABLE_TESTS=ON -DENABLE_VERILOG_TESTS=ON -G Ninja && ninja && ctest
          # Debug the Verilog tests.
          #cmake /systemc-clang -DHDL=ON -DENABLE_TESTS=ON -DENABLE_VERILOG_TESTS=ON -G Ninja && ninja && python3 -B -m pytest -v --color=yes /systemc-clang/tests -k examples #ctest -VV
        
  compile_doxygen_sphinx_docs:
    runs-on: ubuntu-latest
    container: 
      image: "rseac/systemc-clang:clang-11.0.0"
      options: -v ${{github.workspace}}:/systemc-clang
    steps:
      - uses: actions/checkout@v2
      - name: Run doxygen
        run: |
          cd /systemc-clang-build 
          cmake /systemc-clang -DHDL=ON -DENABLE_TESTS=ON -DENABLE_VERILOG_TESTS=ON -DBUILD_DOC=ON -G Ninja && ninja docs
